GET http://localhost:3082/pincode/127.0.0.1
###

GET http://localhost:3082/broadcast


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "powerOff"
}

###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "serverOff"
}


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "serverOff"
}


###
POST http://localhost:3082/initChain
Content-Type: application/json

{
    "CN":"mobile"
}

###


GET http://localhost:3082/getBlockChain


###


GET http://localhost:3082/clearBlockChain


###
POST http://localhost:3082/initChain
Content-Type: application/json

{
    "CN":"mobile"
}