
###
POST http://localhost:3082/initChain
Content-Type: application/json

{
    "CN":"robot"
}

###
POST http://localhost:3000/makeBlock
Content-Type: application/json

{
    "publicKey": { "CA": "TEST", "CN": "TEST", "PUBKEY": "046925288ba597a889c6cba4d0123a028e6b1446fdc346fb70c43a8d643cf638" }
}

###

POST http://localhost:3000/addBlock
Content-Type: application/json

{
    "block":{
  "index": 1,
  "timestamp": 1539090746906,
  "previousHash": "b5c069de73f93dc4eb8ce8925e16b9103aafec1c698005c866f5d710145bbcf7",
  "pubkey": {
    "CA": "TEST",
    "CN": "TEST",
    "PUBKEY": "046925288ba597a889c6cba4d0123a028e6b1446fdc346fb70c43a8d643cf638"
  },
  "hash": "041286eea2265ebe80d5f5168093ba2ed165293e7b65d409c3b726b363486299",
  "signature": "Cp5NYQNduxWQ/YFWwENdgnQMvOk3Vv3O/2SNJEoMiRoyywQhOEH7uf43WObaBNKisU4QlujAKsDxyLhya3a5aM2Dra6XXSC/07BV8FONZ2kFTbBimz+fZ5pvJ+Xy1XS9Ldbm3QpQE/BKxNm/b9NJ7ucquaTexzlTvG8G0UGzPfh3rjGIx2UEPumW3FUagSNYtDs5UYhyeXevYrOptH5swT3HfjcbdFteBP3Gk+33HVknYefBxghY8g8qGickh7ltFDDUIaKNs14NO+JDXVwfrhjnSfZ+NAM6krqteaDtn1hsKEEy9tdAwPmdZygXjP0pzgmkFB8PUDldMnWvTHWC9M+BaWm7B1YvigGf6zmGC0NNKbit39OE2xcrpWy01vMUSY+q3mbCwUS/Vy58lL2HxeEX1EZNVFNdeWc2nr8n4dUizNCgZT9xpY35qy0Be/mykb1ud8azyuGn6Fe5f/nuVWOp01cLNzAR1zn8rpCBGofjLOHD8NugNYbYlvkGkh6KNt5qdTa/bNCboHgQCZgBlkPB++HR0f1751Rh2tLyyYOhFWgOZue/zrCyK8zNGT3/6Ll4oI0Mv8bVO2dKyQsP2XZ8MNAA8ZCLjUHxgOzHIiYaU6UyztbYSrhJrq6xShzPSnyr0iJ0Xuzp6r4TIYPrfZF7yHNejUYpLW2rcfD8neo="
}
}

###
GET http://127.0.0.1:3082/nfcTag

###

GET http://127.0.0.1:3082/nfcCheck

###
GET http://localhost:3082/pincode/192.168.43.118

###

POST http://localhost:3082/confirmPin
Content-Type: application/json

{
  "pin": "56ec1b",
  "secret": "IEVYhZBPWPC8eu1zykU2Pp0Xc76WCN8C85SS7xOuSNYJA/oUANiRt3Sm/AvJJWAWj1dfgtRTI8yuTOKRl/wxde/rZyQWPmHwkqO5d8a1qEavnwyTlHmqxyb+sTqQZAgZlErdHjuRetsvQBC+xjbIAi3U34yMpgvLVDvcgjG02XL98GMiKP/OdCnVw3qmFgAwOKId5HlbfWYY3ZMJts6y9bE5eAD/eNor1y6L/A==",
  "ip": "192.168.43.118",
  "CN": "light"
}
###

###
GET http://127.0.0.1:3082/nfcClear

###
GET http://localhost:3082/broadcast


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "powerOff"
}

###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "serverOff"
}


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "serverOff"
}


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"192.168.43.118",
    "data" : "artik_led_control,38,1"
}


###

GET http://192.168.219.151:3082/getBlockChain

###

POST http://192.168.219.151:3000/getBlockchain


###

GET http://192.168.43.100:3082/reset

###

GET http://192.168.43.107:3082/reset


###

GET http://192.168.43.106:3082/reset


###

GET http://localhost:3082/clearBlockChain


###
POST http://192.168.43.1:3082/replaceBlockchain
Content-Type: application/json

{
    "blk0":"blocks/0.blk",
    "blk1":"blocks/1.blk",
    "blk2":"blocks/2.blk",
    "blk3":"blocks/3.blk",
    "blk4":"blocks/4.blk"
}

###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"192.168.43.225",
    "data" : "led_control,38,1"
}