
###
POST http://localhost:3082/initChain
Content-Type: application/json

{
    "CN":"mobile"
}

###
GET http://192.168.0.110:3082/nfcTag

###
GET http://localhost:3082/pincode/192.168.0.110

###

POST http://localhost:3082/confirmPin
Content-Type: application/json

{
  "pin": "22eec0",
  "secret": "GsRfc0dfwv8wgIRzeG2f2hiG2KKh1WqJz5s59JrST+evGYepLh+0N065sTaXt2rZhM/b4qkLLnHND1gjroa8bm7HlKMfCZx/wvvqdfv6zbRncp6EV/R2cmBtBDjbPTeXs8eg9Sydya2ACsHOwbg26GAl2iOKqd68Hv1fOl/YZBTvcD2FCpmtCu4gs7SuHO2oiGWMpKtGmPimC7hA3kNqGZ98MJgUlWnEQU9MwA==",
  "ip": "192.168.0.110",
  "CN": "robot"
}
###

###
GET http://192.168.0.110:3082/nfcClear

###
GET http://localhost:3082/broadcast


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "powerOff"
}

###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "serverOff"
}


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"127.0.0.1",
    "data" : "serverOff"
}


###
POST http://localhost:3082/control
Content-Type: application/json

{
    "ip":"192.168.43.118",
    "data" : "artik_led_control,38,1"
}


###

GET http://localhost:3082/getBlockChain


###

POST http://localhost:3000/getBlockchain


###

GET http://localhost:3082/clearBlockChain

